import fs from "fs";
import { execFileSync } from "node:child_process";
import path from "path";
import { fileURLToPath } from "url";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { nodePolyfills } from "vite-plugin-node-polyfills";
import { VitePWA } from "vite-plugin-pwa";

const rootDir = path.dirname(fileURLToPath(import.meta.url));

// The build line's baseline (TC-840): the shared web/desktop/mobile version
// frontend/package.json owns, the commit being built, and the channel
// (VITE_EXO_CHANNEL for the pipeline; `vite dev` reports "dev"). Native
// targets override the version and build with the bundle's own numbers.
// package.json is a known file: the cast names its one field, nothing else.
const pkg = JSON.parse(fs.readFileSync(path.join(rootDir, "package.json"), "utf8")) as { version?: string };
const exoBuildInfo = {
  version: pkg.version,
  commit:
    process.env.VITE_EXO_BUILD_COMMIT ??
    process.env.CF_PAGES_COMMIT_SHA ??
    process.env.GITHUB_SHA ??
    (() => {
      try {
        return execFileSync("git", ["rev-parse", "HEAD"], { cwd: rootDir }).toString().trim();
      } catch {
        return undefined;
      }
    })(),
  channel: process.env.VITE_EXO_CHANNEL,
};

export default defineConfig(({ command }) => ({
  define: {
    __EXO_BUILD_INFO__: JSON.stringify({ ...exoBuildInfo, channel: exoBuildInfo.channel ?? (command === "serve" ? "dev" : undefined) }),
  },
  // The client-side TEE verifier (@redpill-ai/verifier + @peculiar/x509) is
  // Node-oriented and uses `Buffer` for base64↔bytes and ASN.1/cert parsing.
  // Vite externalizes Node builtins in the browser, which silently broke the
  // GPU cert-chain check and an on-chain quote encoding. Polyfill the globals.
  plugins: [
    {
      name: "tinychat-agent-artifacts",
      apply: "build",
      buildStart() {
        for (const script of ["build-agent-skills.mjs", "build-agent-setup.mjs"]) {
          execFileSync("node", [path.join(rootDir, "../scripts", script)], { stdio: "inherit" });
        }
      },
    },
    nodePolyfills({ globals: { Buffer: true, process: true, global: true } }),
    react(),
    // Installable web app (PWA). Builds dist/manifest.webmanifest (linked from index.html) and a Workbox
    // service worker, dist/sw.js, that precaches the app shell. Registration is ours, not the plugin's
    // (src/lib/pwa.ts): the same dist is bundled into the Tauri and Capacitor shells, which must never
    // register it, and an update waits for the user's "Reload" instead of swapping the shell under them.
    VitePWA({
      registerType: "prompt",
      injectRegister: false,
      // `vite dev` serves no worker unless VITE_PWA_DEV=true (src/lib/pwa.ts checks the same flag).
      devOptions: { enabled: process.env.VITE_PWA_DEV === "true" },
      manifest: {
        id: "/chat",
        // The product is Exo; the in-app UI still says "TinyCloud Chat" until the rename (TC-526).
        name: "Exo",
        short_name: "Exo",
        description: "Private chat and meeting memory on TinyCloud.",
        start_url: "/chat",
        scope: "/",
        display: "standalone",
        // A manifest takes one color: Day's --background (lib/theme.ts THEME_COLOR). index.html's
        // theme-color metas follow light/dark at runtime.
        theme_color: "#FFFFFF",
        background_color: "#FFFFFF",
        categories: ["productivity"],
        // Generated by mobile/scripts/brand-assets.py from the same mark as the mobile app icons.
        icons: [
          { src: "/icons/pwa-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "/icons/pwa-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          { src: "/icons/maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
          { src: "/icons/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
      },
      // globPatterns below already picks up the icons and the manifest.
      includeManifestIcons: false,
      workbox: {
        // Precache the app shell only: index.html, every JS/CSS chunk (lazy ones included, so an
        // offline launch never misses a chunk), the icons and the display font. /agents/* is
        // published docs, not the app.
        globPatterns: ["**/*.{html,js,css,wasm,png,svg,ico,webmanifest,woff2}"],
        globIgnores: ["agents/**"],
        // The main chunk carries the TinyCloud SDK's inlined WASM (~7.4 MB today); Workbox skips
        // anything over its 2 MiB default, which would leave the shell unable to boot offline.
        maximumFileSizeToCacheInBytes: 24 * 1024 * 1024,
        // App routes (/, /chat/*) are client-side: serve the precached index.html for navigations.
        navigateFallback: "index.html",
        // ...except the static /agents docs (and /api, should one ever be same-origin). Precached files
        // still win: their route is registered first. Mirrors public/_redirects.
        navigateFallbackDenylist: [/^\/agents(?:\/|$)/, /^\/api(?:\/|$)/],
        // No runtimeCaching on purpose. Nothing outside the precache is intercepted, so API and
        // cross-origin traffic (api.tinycloud.chat, the TinyCloud nodes, OpenKey, RedPill, Google,
        // Fireflies …) always goes straight to the network, never to a cache.
        runtimeCaching: [],
        cleanupOutdatedCaches: true,
        // The first install takes control at once (so the next offline launch works); an UPDATE
        // waits (skipWaiting: false) until the page asks for it — see src/lib/pwa.ts.
        clientsClaim: true,
        skipWaiting: false,
      },
    }),
  ],
  resolve: {
    alias: {
      // Redirect @tinycloud/node-sdk/core → @tinycloud/web-sdk in the browser
      // bundle. agentDelegation.ts imports serializeDelegation from node-sdk/core
      // (to avoid web-sdk's HTMLElement at test load time), but node-sdk/core
      // bundles Node.js file-system code (existsSync, path.join) that can't work
      // in a Vite browser build. web-sdk re-exports serializeDelegation without
      // the Node.js deps, so it's the right target for the browser build.
      // In bun test (where HTMLElement is absent) this alias does NOT apply, so
      // tests continue using node-sdk/core as intended.
      "@tinycloud/node-sdk/core": "@tinycloud/web-sdk",
      "@": path.resolve(rootDir, "./src"),
    },
  },
  optimizeDeps: {
    exclude: ["@tinycloud/web-sdk"],
  },
  server: {
    port: 5186,
    allowedHosts: true,
    ...(fs.existsSync("./localhost.pem") && {
      https: {
        key: fs.readFileSync("./localhost-key.pem"),
        cert: fs.readFileSync("./localhost.pem"),
      },
    }),
  },
}));
