#!/usr/bin/env bash
# Regenerates ExoCapture's Debug-simulator-only test clips (SimulatorAudioClips.swift).
# Offline only: `say -o` renders to a file and plays nothing; the sweep is computed in Python.
# Provenance: both clips are generated here (macOS speech synthesis of our own sentence, and a
# synthetic sweep), so there is no third-party recording or licence to carry.
set -euo pipefail
out="$(cd "$(dirname "$0")/.." && pwd)/Packages/ExoCapture/Sources/ExoCapture/SimulatorAudioClips.swift"
tmp="$(mktemp -d)"; trap 'rm -r "$tmp"' EXIT

say -o "$tmp/speech.aiff" "Testing the Exo recorder. The halo should move when I speak."
ffmpeg -loglevel error -y -i "$tmp/speech.aiff" -ac 1 -ar 16000 -c:a pcm_s16le "$tmp/speech.wav"

python3 - "$tmp/sweep.wav" <<'PY'
import math, struct, sys, wave
rate, step_s = 8000, 1.0
levels_db = [-40, -34, -28, -22, -16, -10, -6]
total = step_s * len(levels_db)
n = int(rate * total)
f0, f1 = 200.0, 2000.0
frames = bytearray()
for i in range(n):
    t = i / rate
    phase = 2 * math.pi * (f0 * t + (f1 - f0) * t * t / (2 * total))
    step = min(int(t / step_s), len(levels_db) - 1)
    into = t - step * step_s
    ramp = min(1.0, into / 0.02, (step_s - into) / 0.02)  # 20 ms ramps keep steps click-free
    amp = 10 ** (levels_db[step] / 20) * max(0.0, ramp)
    frames += struct.pack("<h", round(amp * math.sin(phase) * 32767))
with wave.open(sys.argv[1], "wb") as w:
    w.setnchannels(1); w.setsampwidth(2); w.setframerate(rate); w.writeframes(bytes(frames))
PY

{
  echo "#if DEBUG && targetEnvironment(simulator)"
  echo "// Generated by mobile/ios/scripts/gen-sim-audio.sh; do not edit. WAV, 16-bit mono PCM."
  echo "// speech: macOS \`say\` rendering of our own sentence, 16 kHz. sweep: 200 Hz to 2 kHz, 8 kHz,"
  echo "// seven 1 s steps at -40, -34, -28, -22, -16, -10, -6 dBFS."
  echo "enum SimulatorAudioClips {"
  for name in speech sweep; do
    echo "    static let ${name}Base64 = \"\"\""
    base64 < "$tmp/$name.wav" | fold -w 100
    echo "\"\"\""
  done
  echo "}"
  echo "#endif"
} > "$out"
ls -l "$tmp"/*.wav >&2; ls -l "$out" >&2
