export const FINAL_COPY = {
  listening: "Listening",
  resting: "Resting · tap to continue",
  interrupted: "Interrupted",
  tapToResume: "Tap to resume",
  microphoneOff: "Microphone off",
  idle: "Ready",
  starting: "Starting…",
  saving: "Saving…",
  stopping: "Saving…",
  discarding: "Discarding…",
  noSoundFrom: (input: string) => `No sound from ${input}`,
  resumesWhenCallEnds: "Resumes when the call ends",
  resumeBlocked: "Microphone unavailable. Check your audio input.",
  denied: "Microphone access is off. Open Settings to allow access.",
  openSettings: "Open Settings",
  stopAt: (text: string) => `Stops at ${text}`,
  stoppedAtThreeHours: "Stopped at 3 hours",
  comingNextUpdate: "Coming with the next update",
  needsApp: "needs the app",
  onThisPhone: "on this phone",
  onThisMac: "on this Mac",
  sealedEnclave: "sealed enclave",
  assemblyAi: "AssemblyAI",
  identifySpeakers: "Identify speakers",
  powerfulOnly: "Powerful only",
  whisperUnavailable: "Get Whisper for this Mac",
  modelUnavailable: "Get the on-device model",
  modes: {
    skipName: "Skip",
    localName: "Local",
    privateName: "Private",
    powerfulName: "Powerful",
    speakersName: "AssemblyAI · speakers",
    audioOnly: "audio only",
    skipCaption: { phone: "Just the recording, kept on this phone.", desktop: "Just the recording, saved to your space.", web: "Just the recording, saved to your space." },
    skipExplanation: "Only the audio is saved. Transcribe it later if you like.",
    localPhoneCaption: "Nothing leaves it; a little slower.",
    localDesktopCaption: "Whisper on this Mac, after you stop.",
    localPhoneExplanation: "An on-device model transcribes it. Nothing leaves your phone; slower and less accurate.",
    localDesktopExplanation: "Whisper transcribes on this Mac after you stop, and nothing leaves the machine. Names the selected model and points to Settings.",
    localWebExplanation: "Runs on your phone or Mac in the Exo app. Not available in the browser.",
    privateCaption: "Fast, accurate, and sealed from Exo.",
    privateExplanation: "Transcribed in a sealed hardware enclave. Not even Exo can read it. Fast and accurate.",
    powerfulCaption: "Most accurate. Audio deleted after processing.",
    powerfulExplanation: "Uploaded to AssemblyAI, a third-party service: the most accurate, with speaker labels. Audio is deleted after processing.",
  },
} as const;
