export const NOTES_COPY = {
  noteThisMoment: "Note this moment",
  viewNotes: "View notes",
  momentPlaceholder: (time: string) => `What's happening at ${time}?`,
  momentPendingPlaceholder: "What's happening?",
  momentLabel: (time: string) => `Note for ${time}`,
  momentLabelPending: "Note for this moment",
  saveMoment: "Save moment",
  momentNoted: "Moment noted",
  notesTitle: "Notes",
  notesDone: "Done",
  saved: "Saved",
  noteLoading: "Loading note…",
  noteLoadFailed: "Your note could not be loaded.",
  noteSaveFailed: "Your note could not be saved. What you typed is kept; closing the notes tries again.",
  noteNotSaved: "Note not saved",
  noteNotSavedAlert: "Note not saved. Open View notes to try again, or tap Done again to finish without it.",
  noteNotSynced: "Note not synced yet",
  viewTabs: "Notes view",
  write: "Write",
  preview: "Preview",
  noteField: "Notes, Markdown",
  notePlaceholder: "Jot it down. Markdown works.",
  nothingWritten: "Nothing written yet.",
  rendering: "Rendering…",
  previewFailed: "The preview could not be drawn.",
  tryAgain: "Try again",
  pauseRecording: (time: string) => `Pause recording, ${time}`,
  resumeRecording: (time: string) => `Resume recording, ${time}`,
  momentFailed: (message: string) => `Could not mark this moment: ${message}`,
  formatting: "Formatting",
  markdownHint: "Markdown",
  tools: {
    heading: "Heading",
    bold: "Bold",
    italic: "Italic",
    bullets: "Bulleted list",
    checklist: "Checklist",
    quote: "Quote",
  },
  discardLoss: (time: string, withNotes: boolean) =>
    withNotes
      ? `You'll lose ${time} of audio and your notes. This can't be undone.`
      : `You'll lose ${time} of audio. This can't be undone.`,
} as const;
