/** Every line of text on the Soft Capture home that the library's own rows do not already say (TC-871). */
export const HOME_COPY = {
  heading: "Capture",
  library: "Library",
  inProgress: "In progress",
  recent: "Recent",
  seeAll: "See all",
  recentEmpty: "Your recordings appear here",
  loadingRecent: "Loading your recent captures…",
  recentFailed: "Couldn’t load your recent captures.",
  retryRecent: "Try again",
  voiceNoteTitle: "Voice note",
  onPhoneOne: "1 voice note on this phone",
  onPhoneMany: (count: number) => `${count} voice notes on this phone`,
  notInSpace: "Not in your space yet",
  saveNow: "Save now",
  willFinish: "Exo will finish it automatically",
  willRetry: "Exo will retry when it next opens",
  timedOutMeta: "Saving… · kept on this phone",
  recoveryFailedMeta: "Couldn't recover this recording",
  writeFailedMeta: "Couldn't save all of this recording",
  needsAttention: "Needs attention",
  opensDetails: "Opens details",
  scanFailure:
    "Exo couldn't check for unfinished recordings. It will try again when it next opens.",
  upload: "Upload",
  recorder: "Recorder",
  meeting: "Meeting",
  recordLabel: "Recorder, record a voice note",
  openRecorderLabel: "Open recorder",
  uploadLabel: "Upload audio",
  meetingLabel: "Send a notetaker to a meeting",
  close: "Close",
  recoveryFailedSheet: {
    title: "Couldn't recover this recording",
    body: "Exo couldn't finish saving this recording. It will try again when it next opens.",
  },
  writeFailedSheet: {
    title: "Couldn't save all of this recording",
    body: "This phone stopped saving the recording partway through. What was recorded up to that point is kept; the rest was not recorded.",
  },
} as const;
